# Default settings: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

default: true # Default state for all rules

MD010: false # MD010/no-hard-tabs - Disabled as it is linting latex blocks
MD025: false # MD025/single-title/single-h1 - Multiple top-level headings in the same document
MD034: false # MD034/no-bare-urls - Interferes with URLs
MD045: false # MD045/no-alt-text - Quarto doesn't output alt text on compute blocks

MD033: # MD033/no-inline-html
  allowed_elements:
    - callout
    - a
    - figure
    - img
    - ref
    - sup
    - plotly
    - todo
    - plot
    - feature
    - bigfeature
    - cell
    - div
    - td
    - p
    - span
    - script
    - style

MD013: # MD013/line-length
  line_length: 100000000000000
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true # Include code blocks
  tables: true # Include tables
  headings: true # Include headings
  headers: true # Include headings
  strict: false # Strict length checking
  stern: false # Stern length checking