baseURL: "https://osquant.com"
languageCode: "en-us"
title: "Open Source Quant"
theme: "osquant"
FootnoteReturnLinkContents: "↑"

disableKinds: ["taxonomy", "section"]
ignoreErrors: ["error-disable-taxonomy"]
ignoreFiles: [ "\\.qmd$", "\\.py$" ]

params:
  gtag: G-SSDJH3F7EZ
  description: A site where quants write about mathematics, engineering and finance.
  site_twitter_handler: '@DrAdrian'
  images:
    - feature.png

sitemap:
  changefreq: weekly
  filename: sitemap.xml

markup:
  highlight:
    # Code syntax highlighting. Examples of each style can be found
    # here https://xyproto.github.io/splash/docs/
    style: "github"
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  author: authors
  category: categories

security:
  funcs:
    getenv:
      - ^HUGO_

menu:
  # The main menu in the top navigation bar
  main:
    - identifier: mathematics
      name: Mathematics
      url: /categories/mathematics/
      weight: 1
    - identifier: engineering
      name: Engineering
      url: /categories/engineering/
      weight: 2
    - identifier: finance
      name: Finance
      url: /categories/finance/
      weight: 3
    # - identifier: about
    #   name: About
    #   url: /about
    #   weight: 4
    # - identifier: contribute
    #   name: Contribute
    #   url: /contribute
    #   weight: 5
  
  # Footer menus
  footer_categories:
    - identifier: mathematics
      name: Mathematics
      url: /categories/mathematics/
      weight: 1
    - identifier: engineering
      name: Engineering
      url: /categories/engineering/
      weight: 2
    - identifier: finance
      name: Finance
      url: /categories/finance/
      weight: 3

  footer_dev:
    - identifier: style-guide
      name: Style Guide
      url: /visual-style-guide/
      weight: 1
