baseURL: "/"
languageCode: "en-us"
title: "Open Source Quant"
theme: "osquant"
FootnoteReturnLinkContents: "↑"

markup:
  highlight:
    style: "monokailight" # dracula
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  author: authors

menu:
  author_guide:
  - identifier: visual
    name: Visual Style Guide
    url: /visual-style-guide/