baseURL: "https://osquant.co"
languageCode: "en-us"
title: "Open Source Quant"
theme: "osquant"
FootnoteReturnLinkContents: "↑"

disableKinds: ["taxonomy", "section"]
ignoreErrors: ["error-disable-taxonomy"]

params:
  gtag: G-SSDJH3F7EZ
  github_content: https://github.com/robolyst/osquant/tree/main/content/

sitemap:
  changefreq: weekly
  filename: sitemap.xml

markup:
  highlight:
    style: "monokailight" # dracula
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  author: authors

menu:
  author_guide:
  - identifier: visual
    name: Visual Style Guide
    url: /visual-style-guide/