#!/bin/bash

# Run `./invoke build` to build the testing image.

if [ "$1" = "build" ]; then
    docker build . --tag osquant
elif [ "$1" = "shell" ]; then
    docker run -it --rm --volume $(pwd):/app \
    osquant sh
elif [ "$1" = "check" ]; then
    docker run -it --rm --volume $(pwd):/app \
    osquant markdownlint content
elif [ "$1" = "format" ]; then
    docker run -it --rm --volume $(pwd):/app \
    osquant markdownlint content --fix
elif [ "$1" = "vale" ]; then
    docker run -it --rm -v $(pwd):/app \
    -w /app \
    jdkato/vale "${@:2}" 
fi
