#!/bin/bash

set -e

docker run -it --rm \
    --volume $(pwd):/app \
    -p 1313:1313 \
    --workdir /app \
    $(docker build -q .devcontainer) \
    quarto preview --host 0.0.0.0 --port 1313 --no-browser