# name: Style checker

# on: [push]

# jobs:
#   style-checker-job:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  
#       - name: Check out repository code
#         uses: actions/checkout@v4

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: install dependencies
#         run: |
#           npm install -g markdownlint-cli

#       - name: run style checks
#         run: bash check
